services:
  app:
    image: ghcr.io/haiquanng/tutora-zalo-bot:latest
    container_name: tutora-zalo-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
